name: Update USTC IP Blacklist
on:
  schedule:
    - cron: '0 0 * * *'     # 每天 UTC 00:00 触发:contentReference[oaicite:4]{index=4}
  workflow_dispatch:       # 支持手动触发
permissions:
  contents: write          # 允许写入仓库内容（用于 git push）:contentReference[oaicite:5]{index=5}
jobs:
  update-blacklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download USTC IP blacklist
        run: |
          curl -sS -o ip_blacklist.txt https://blackip.ustc.edu.cn/txt.php

      - name: Configure Git author
        run: |
          git config user.name "yvesyc"
          git config user.email "yvesyc@hotmail.com"

      - name: Commit and push changes if any
        run: |
          # 检查 ip_blacklist.txt 是否有更改
          if git diff --quiet --exit-code ip_blacklist.txt; then
            echo "No changes in ip_blacklist.txt, skipping commit"
          else
            git add ip_blacklist.txt
            git commit -m "Update USTC IP blacklist"
            git push origin main
          fi
